sonar.projectKey=cloudctlio_cloudctl
sonar.organization=cloudctlio

sonar.projectName=cloudctl
sonar.projectVersion=0.2.0

sonar.sources=cloudctl
sonar.tests=tests
sonar.exclusions=**/__pycache__/**,**/*.pyc
sonar.test.exclusions=**/tests/**

sonar.python.version=3.11,3.12
sonar.python.coverage.reportPaths=coverage.xml
